[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."generate"]
  external_node_modules = ["pg"]
  timeout = 26

[functions."regenerate-piece"]
  external_node_modules = ["pg"]
  node_bundler = "esbuild"
  timeout = 26

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
